server:
  port: 8888
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/erp_invoice?useSSL=false&useUnicode=true&characterEncoding=UTF8
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  #解决springboot和swagger的冲突
mybatis-plus:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
logging:
  level:
    com.pax.offline_invoice.dao: debug    #打印出mapper执行的sql语句
#自定义配置参数
#jscode2session: https://api:weixin:qq:com/sns/jscode2session
#appId: wxe52d0f50f14898dd
#secret: 8bbcfb9c34454454b0e14f0457441736


